language: java
#sudo: false
script: "jdk_switcher use oraclejdk8; cd Phosphor; export INST_HOME=$JAVA_HOME/jre; mvn -Ddacapo.skip=false verify"
after_success:
  - cd phosphor; mvn install --settings ~/settings.xml
